---
- name: Add an Apt signing key docker
  apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present
   
- name: Install repo docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
   
- name: Install packages dependencies
  apt:
    name:
        - docker-ce
    state: present

- name: Make sure docker service is running
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Remove file config.toml
  file:
    path: /etc/containerd/config.toml
    state: absent

- name: Enable the Containerd service and start it
  systemd:
    name: containerd
    state: restarted
    enabled: yes