---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - net-tools

- name: Disable SWAP in fstab (Kubeadm requirement)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Create an empty file for Kubernetes sysctl params
  copy:
    content: ""
    dest: /etc/sysctl.d/k8s.conf
    force: no

- name: Configure sysctl params for Kubernetes
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
  with_items:
    - 'net.bridge.bridge-nf-call-iptables  = 1'
    - 'net.ipv4.ip_forward                 = 1'
    - 'net.bridge.bridge-nf-call-ip6tables = 1'

- name: Apply sysctl params without reboot
  command: sysctl --system

- name: Add an Apt signing key docker
  apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present
   
- name: Install repo docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distribution_release }} stable"
    state: present
   
- name: Install packages dependencies
  apt:
    name:
        - docker-ce
    state: present

- name: Make sure docker service is running
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Usermod user group docker
  command: usermod -aG docker ${USER}

- name: Remove file config.toml
  file:
    path: /etc/containerd/config.toml
    state: absent

- name: Enable the Containerd service and start it
  systemd:
    name: containerd
    state: restarted
    enabled: yes
      
- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Add Kubernetes apt-key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ version_k8s }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true

- name: Add apt repository for stable version
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ version_k8s }}/deb/ /"
    state: present
    update_cache: yes

- name: Install k8s
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - kubelet 
    - kubeadm 
    - kubectl

- name: Enable the kubelet service and start it
  systemd:
    name: kubelet
    state: restarted
    enabled: yes

- name: Add an Apt signing key helm
  apt_key:
     url: https://baltocdn.com/helm/signing.asc
     state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    update_cache: yes

- name: Install packages helm
  apt:
    name:
        - helm
    state: present

- name: Prevent packages from being upgraded
  command: apt-mark hold kubectl kubeadm kubelet 

- include_tasks: master.yml
  when: master == true

- include_tasks: workers.yml
  when: workers == true