---
- name: Capture ip
  shell: echo $(ip a | awk '/inet / && !/127.0.0.1/ && !/10.0.2.15/ {split($2, a, "/"); print a[1]}' |head -n1)
  register: result_ip

- name: Display Ips
  debug:
    msg: "{{ result_ip.stdout }}"

- name: Set ip
  set_fact:
    ip: "{{ result_ip.stdout }}"

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - net-tools

- include_tasks: ha_proxy.yml
  when: ha_proxy == true

- include_tasks: dependencies_k8s.yml
  when: single_controlplane == true or multi_controlplane == true or workers == true or join_masters == true

- include_tasks: single.yml
  when: single_controlplane == true

- include_tasks: multi.yml
  when: multi_controlplane == true 

- include_tasks: workers.yml
  when: workers == true

- include_tasks: join_masters.yml
  when: join_masters == true
